### ISSUE TITLE
HttpError

### ISSUE THREAD

**Issue by komodotext** [joeyhage/homebridge-alexa-smarthome#20]
After linking the Amazon account, I saw the confirmation that my 'amazon alexa cookie was successfully retrieved' However, it did not show up in the logs. I tried uninstalling and reinstalling the plugin and now recieving a HttpError. Unable to load the localhost:2345 page now.

I did have an issue with the wrong IP address, which was later fixed in the configuration. 

8/31/2023, 4:10:11 PM] Homebridge v1.6.1 (HAP v0.11.1) (Homebridge 632D) is running on port 51319.
[8/31/2023, 4:10:11 PM] [HomebridgeAlexaSmartHome] Failed to initialize. Error: You can try to get the cookie manually by opening http://196.168.1.5:2345/ with your browser.
    at /var/lib/homebridge/node_modules/homebridge-alexa-smarthome/node_modules/alexa-cookie2/alexa-cookie.js:390:38
    at Server.<anonymous> (/var/lib/homebridge/node_modules/homebridge-alexa-smarthome/node_modules/alexa-cookie2/lib/proxy.js:379:30)
    at Object.onceWrapper (node:events:627:28)
    at Server.emit (node:events:513:28)
    at emitListeningNT (node:net:1774:10)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
[8/31/2023, 4:10:11 PM] [HomebridgeAlexaSmartHome] After initialization - HttpError(Error getting smart home devices. Reason: Cookie invalid, Renew unsuccessful)
[8/31/2023, 4:15:12 PM] [Homebridge UI] Changes to config.json saved.
[8/31/2023, 4:30:53 PM] [Homebridge UI] Changes to config.json saved.
[8/31/2023, 4:41:40 PM] [Homebridge UI] Homebridge restart request received
[8/31/2023, 4:41:40 PM] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[8/31/2023, 4:41:40 PM] [Homebridge UI] Sending SIGTERM to Homebridge
[8/31/2023, 4:41:40 PM] Got SIGTERM, shutting down Homebridge...
[8/31/2023, 4:41:45 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[8/31/2023, 4:41:50 PM] [HB Supervisor] Restarting Homebridge...
[8/31/2023, 4:41:50 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[8/31/2023, 4:41:50 PM] [HB Supervisor] Started Homebridge v1.6.1 with PID: 17150
[8/31/2023, 4:41:52 PM] Loaded config.json with 0 accessories and 2 platforms.
[8/31/2023, 4:41:52 PM] Loaded 0 cached accessories from cachedAccessories.
[8/31/2023, 4:41:52 PM] ---
[8/31/2023, 4:41:52 PM] Loaded plugin: homebridge-alexa-smarthome@0.1.0
[8/31/2023, 4:41:52 PM] Registering platform 'homebridge-alexa-smarthome.HomebridgeAlexaSmartHome'
[8/31/2023, 4:41:52 PM] ---
[8/31/2023, 4:41:52 PM] Loading 2 platforms...
[8/31/2023, 4:41:52 PM] [HomebridgeAlexaSmartHome] Initializing HomebridgeAlexaSmartHome platform...
Setup Payload:
X-HM://00241BD6RA51K
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       

                       
[8/31/2023, 4:41:53 PM] [HomebridgeAlexaSmartHome] Failed to initialize. Error: You can try to get the cookie manually by opening http://192.168.1.5:2345/ with your browser.
    at /var/lib/homebridge/node_modules/homebridge-alexa-smarthome/node_modules/alexa-cookie2/alexa-cookie.js:390:38
    at Server.<anonymous> (/var/lib/homebridge/node_modules/homebridge-alexa-smarthome/node_modules/alexa-cookie2/lib/proxy.js:379:30)
    at Object.onceWrapper (node:events:627:28)
    at Server.emit (node:events:513:28)
    at emitListeningNT (node:net:1774:10)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
[8/31/2023, 4:41:53 PM] [HomebridgeAlexaSmartHome] After initialization - HttpError(Error getting smart home devices. Reason: Cookie invalid, Renew unsuccessful)
[8/31/2023, 4:41:53 PM] Homebridge v1.6.1 (HAP v0.11.1) (Homebridge 632D) is running on port 51319.
[8/31/2023, 4:44:36 PM] [HomebridgeAlexaSmartHome] After initialization - HttpError(Error getting smart home device state. Reason: Timeout)
[8/31/2023, 4:45:30 PM] [Homebridge UI] Changes to config.json saved.
[8/31/2023, 4:46:26 PM] [Homebridge UI] Homebridge restart request received
[8/31/2023, 4:46:27 PM] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[8/31/2023, 4:46:27 PM] [Homebridge UI] Sending SIGTERM to Homebridge
[8/31/2023, 4:46:27 PM] Got SIGTERM, shutting down Homebridge...
[8/31/2023, 4:46:32 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[8/31/2023, 4:46:37 PM] [HB Supervisor] Restarting Homebridge...
[8/31/2023, 4:46:37 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[8/31/2023, 4:46:37 PM] [HB Supervisor] Started Homebridge v1.6.1 with PID: 17339
[8/31/2023, 4:46:38 PM] Loaded config.json with 0 accessories and 2 platforms.
[8/31/2023, 4:46:38 PM] Loaded 0 cached accessories from cachedAccessories.
[8/31/2023, 4:46:38 PM] ---
[8/31/2023, 4:46:38 PM] Loaded plugin: homebridge-alexa-smarthome@0.1.0
[8/31/2023, 4:46:38 PM] Registering platform 'homebridge-alexa-smarthome.HomebridgeAlexaSmartHome'
[8/31/2023, 4:46:38 PM] ---
[8/31/2023, 4:46:38 PM] Loading 2 platforms...
[8/31/2023, 4:46:38 PM] [HomebridgeAlexaSmartHome] Initializing HomebridgeAlexaSmartHome platform...
Setup Payload:
X-HM://00241BD6RA51K
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 342-36-547 │     
    └────────────┘     
                       
[8/31/2023, 4:46:39 PM] Homebridge v1.6.1 (HAP v0.11.1) (Homebridge 632D) is running on port 51319.
[8/31/2023, 4:46:56 PM] [HomebridgeAlexaSmartHome] After initialization - HttpError(Error getting smart home device state. Reason: Timeout)
[8/31/2023, 4:50:25 PM] [Homebridge UI] Starting terminal session
[8/31/2023, 4:50:35 PM] [Homebridge UI] Terminal session ended.
[8/31/2023, 4:50:35 PM] [Homebridge UI] Homebridge restart request received
[8/31/2023, 4:50:35 PM] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[8/31/2023, 4:50:35 PM] [Homebridge UI] Sending SIGTERM to Homebridge
[8/31/2023, 4:50:35 PM] Got SIGTERM, shutting down Homebridge...
[8/31/2023, 4:50:40 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[8/31/2023, 4:50:45 PM] [HB Supervisor] Restarting Homebridge...
[8/31/2023, 4:50:45 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[8/31/2023, 4:50:45 PM] [HB Supervisor] Started Homebridge v1.6.1 with PID: 17406
[8/31/2023, 4:50:46 PM] Loaded config.json with 0 accessories and 2 platforms.
[8/31/2023, 4:50:46 PM] Loaded 0 cached accessories from cachedAccessories.
[8/31/2023, 4:50:46 PM] ---
[8/31/2023, 4:50:46 PM] Loaded plugin: homebridge-alexa-smarthome@0.1.0
[8/31/2023, 4:50:46 PM] Registering platform 'homebridge-alexa-smarthome.HomebridgeAlexaSmartHome'
[8/31/2023, 4:50:46 PM] ---
[8/31/2023, 4:50:46 PM] Loading 2 platforms...
[8/31/2023, 4:50:46 PM] [HomebridgeAlexaSmartHome] Initializing HomebridgeAlexaSmartHome platform...
Setup Payload:
X-HM://00241BD6RA51K
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       

                       
[8/31/2023, 4:50:47 PM] Homebridge v1.6.1 (HAP v0.11.1) (Homebridge 632D) is running on port 51319.
[8/31/2023, 4:51:05 PM] [HomebridgeAlexaSmartHome] After initialization - HttpError(Error getting smart home device state. Reason: Timeout)
[8/31/2023, 4:51:24 PM] [Homebridge UI] Changes to config.json saved.
[8/31/2023, 4:51:24 PM] [Homebridge UI] Running Command: npm uninstall --save homebridge-alexa-smarthome
[8/31/2023, 4:51:36 PM] [Homebridge UI] Running Command: /opt/homebridge/lib/node_modules/homebridge-config-ui-x/plugin-upgrade-install.sh homebridge-alexa-smarthome 0.1.0 /var/lib/homebridge/node_modules
[8/31/2023, 4:51:57 PM] [Homebridge UI] Changes to config.json saved.
[8/31/2023, 4:53:13 PM] [Homebridge UI] Homebridge restart request received
[8/31/2023, 4:53:14 PM] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[8/31/2023, 4:53:14 PM] [Homebridge UI] Sending SIGTERM to Homebridge
[8/31/2023, 4:53:14 PM] Got SIGTERM, shutting down Homebridge...
[8/31/2023, 4:53:19 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[8/31/2023, 4:53:24 PM] [HB Supervisor] Restarting Homebridge...
[8/31/2023, 4:53:24 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[8/31/2023, 4:53:24 PM] [HB Supervisor] Started Homebridge v1.6.1 with PID: 17517
[8/31/2023, 4:53:25 PM] Loaded config.json with 0 accessories and 2 platforms.
[8/31/2023, 4:53:25 PM] Loaded 0 cached accessories from cachedAccessories.
[8/31/2023, 4:53:25 PM] ---
[8/31/2023, 4:53:25 PM] Loaded plugin: homebridge-alexa-smarthome@0.1.0
[8/31/2023, 4:53:25 PM] Registering platform 'homebridge-alexa-smarthome.HomebridgeAlexaSmartHome'
[8/31/2023, 4:53:25 PM] ---
[8/31/2023, 4:53:25 PM] Loading 2 platforms...
[8/31/2023, 4:53:25 PM] [HomebridgeAlexaSmartHome] Initializing HomebridgeAlexaSmartHome platform...
Setup Payload:
X-HM://00241BD6RA51K
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    
                       
[8/31/2023, 4:53:26 PM] Homebridge v1.6.1 (HAP v0.11.1) (Homebridge 632D) is running on port 51319.
[8/31/2023, 4:53:44 PM] [HomebridgeAlexaSmartHome] After initialization - HttpError(Error getting smart home device state. Reason: Timeout)
[8/31/2023, 4:54:33 PM] [Homebridge UI] Changes to config.json saved.
[8/31/2023, 4:56:43 PM] [Homebridge UI] Changes to config.json saved.
[8/31/2023, 4:59:11 PM] [Homebridge UI] Homebridge restart request received
[8/31/2023, 4:59:11 PM] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[8/31/2023, 4:59:11 PM] [Homebridge UI] Sending SIGTERM to Homebridge
[8/31/2023, 4:59:11 PM] Got SIGTERM, shutting down Homebridge...
[8/31/2023, 4:59:16 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[8/31/2023, 4:59:21 PM] [HB Supervisor] Restarting Homebridge...
[8/31/2023, 4:59:21 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[8/31/2023, 4:59:21 PM] [HB Supervisor] Started Homebridge v1.6.1 with PID: 18245
[8/31/2023, 4:59:23 PM] Loaded config.json with 0 accessories and 2 platforms.
[8/31/2023, 4:59:23 PM] Loaded 0 cached accessories from cachedAccessories.
[8/31/2023, 4:59:23 PM] ---
[8/31/2023, 4:59:23 PM] Loaded plugin: homebridge-alexa-smarthome@0.1.0
[8/31/2023, 4:59:23 PM] Registering platform 'homebridge-alexa-smarthome.HomebridgeAlexaSmartHome'
[8/31/2023, 4:59:23 PM] ---
[8/31/2023, 4:59:23 PM] Loading 2 platforms...
[8/31/2023, 4:59:23 PM] [HomebridgeAlexaSmartHome] Initializing HomebridgeAlexaSmartHome platform...
Setup Payload:
X-HM://00241BD6RA51K
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 342-36-547 │     
    └────────────┘     
                       
[8/31/2023, 4:59:23 PM] Homebridge v1.6.1 (HAP v0.11.1) (Homebridge 632D) is running on port 51319.
[8/31/2023, 4:59:41 PM] [HomebridgeAlexaSmartHome] After initialization - HttpError(Error getting smart home device state. Reason: Timeout)
[8/31/2023, 5:30:37 PM] [Homebridge UI] Changes to config.json saved.
[8/31/2023, 5:30:37 PM] [Homebridge UI] Running Command: npm uninstall --save homebridge-alexa-smarthome
[8/31/2023, 5:30:53 PM] [Homebridge UI] Running Command: /opt/homebridge/lib/node_modules/homebridge-config-ui-x/plugin-upgrade-install.sh homebridge-alexa-smarthome 0.1.0 /var/lib/homebridge/node_modules
[8/31/2023, 5:31:12 PM] [Homebridge UI] Changes to config.json saved.
[8/31/2023, 5:32:47 PM] [Homebridge UI] Homebridge restart request received
[8/31/2023, 5:32:47 PM] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[8/31/2023, 5:32:47 PM] [Homebridge UI] Sending SIGTERM to Homebridge
[8/31/2023, 5:32:47 PM] Got SIGTERM, shutting down Homebridge...
[8/31/2023, 5:32:52 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[8/31/2023, 5:32:57 PM] [HB Supervisor] Restarting Homebridge...
[8/31/2023, 5:32:57 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[8/31/2023, 5:32:57 PM] [HB Supervisor] Started Homebridge v1.6.1 with PID: 18895
[8/31/2023, 5:32:58 PM] Loaded config.json with 0 accessories and 2 platforms.
[8/31/2023, 5:32:58 PM] Loaded 0 cached accessories from cachedAccessories.
[8/31/2023, 5:32:58 PM] ---
[8/31/2023, 5:32:59 PM] Loaded plugin: homebridge-alexa-smarthome@0.1.0
[8/31/2023, 5:32:59 PM] Registering platform 'homebridge-alexa-smarthome.HomebridgeAlexaSmartHome'
[8/31/2023, 5:32:59 PM] ---
[8/31/2023, 5:32:59 PM] Loading 2 platforms...
[8/31/2023, 5:32:59 PM] [HomebridgeAlexaSmartHome] Initializing HomebridgeAlexaSmartHome platform...
Setup Payload:
X-HM://00241BD6RA51K
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 342-36-547 │     
    └────────────┘     
                       
[8/31/2023, 5:32:59 PM] Homebridge v1.6.1 (HAP v0.11.1) (Homebridge 632D) is running on port 51319.
[8/31/2023, 5:33:17 PM] [HomebridgeAlexaSmartHome] After initialization - HttpError(Error getting smart home device state. Reason: Timeout)

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

{
    "bridge": {
        "name": "Homebridge 632D",
        "username": "0E:69:7F:F9:63:2D",
        "port": 51319,
        "pin": "",
        "advertiser": "avahi"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "auth": {
                "refreshInterval": 4,
                "proxy": {
                    "clientHost": "192.168.1.5",
                    "port": 2345
                }
            },
            "devices": [],
            "amazonDomain": "amazon.com",
            "language": "en-US",
            "debug": false,
            "platform": "HomebridgeAlexaSmartHome"
        }
    ]
}

**Screenshots:**

**Environment:**

- **Plugin Version**: homebridge-alexa-smarthome v0.1.0
- **Homebridge Version**: [v1.6.1]
- **Node.js Version**: [v18.16.0]
- **NPM Version**: 
- **Operating System**: Raspbian

**Comment by joeyhage** [comment]
I see a Timeout error in there. One thing you could try is explicitly providing the list of device names you want to link in the plugin config.

**Comment by komodotext** [comment]
See that worked, thanks so much Joey!

**Comment by joeyhage** [comment]
You’re welcome!
